"use client";

import { AlertTriangle, BookOpenText, CheckCircle2, Lightbulb, ShieldAlert } from "lucide-react";

import { PageHeader } from "@/components/page-header";
import { getStrategyRules } from "@/data/mock-data";
import { useStrategy } from "@/providers/strategy-provider";

const sections = [
  {
    title: "What worked",
    icon: CheckCircle2,
    body: "The mock results favor a disciplined trend and momentum stack. Stocks must pass the long-term trend filter before the strategy considers short-term strength, which helps avoid buying weak rebound candidates in this sample."
  },
  {
    title: "Key risks",
    icon: ShieldAlert,
    body: "The approach can lag sharp reversals and may become concentrated in high-momentum technology names. Drawdowns can still be meaningful when the benchmark sells off or when leadership rotates quickly."
  },
  {
    title: "Overfitting warning",
    icon: AlertTriangle,
    body: "The thresholds shown here are educational mock settings. A real implementation would need out-of-sample testing, transaction cost modeling, survivorship-bias controls, and sensitivity analysis before drawing conclusions."
  },
  {
    title: "Possible improvements",
    icon: Lightbulb,
    body: "Next iterations could add regime filters, sector caps, turnover constraints, and clearer trade logs. The most useful near-term improvement is making every rule explainable before adding more parameters."
  }
];

export function ResearchNotesPage() {
  const { strategy } = useStrategy();
  const enabledRules = getStrategyRules(strategy).filter((rule) => rule.enabled);

  return (
    <>
      <PageHeader
        eyebrow="Research Notes"
        title="Interpret the strategy without treating it as advice."
        description="These notes are mock educational explanations for the current configuration. They are not generated by an AI service and are not financial advice."
      />

      <section className="grid gap-6 xl:grid-cols-[420px_1fr]">
        <div className="rounded-md border border-borderSoft bg-panel p-5 shadow-panel">
          <div className="flex items-start gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-md bg-accentSoft text-accent">
              <BookOpenText size={20} />
            </div>
            <div>
              <h2 className="text-base font-semibold tracking-tight">Strategy summary</h2>
              <p className="mt-1 text-sm leading-6 text-textMuted">
                {strategy.name} screens {strategy.universe} stocks against {strategy.benchmark} and
                selects {strategy.portfolioSize.toLowerCase()} using {strategy.weighting.toLowerCase()}.
              </p>
            </div>
          </div>

          <div className="mt-5 space-y-3">
            {enabledRules.map((rule) => (
              <div key={rule.label} className="rounded-md border border-borderSoft bg-panelMuted p-3">
                <div className="text-sm font-semibold">{rule.label}</div>
                <div className="mt-1 text-sm leading-6 text-textMuted">{rule.value}</div>
              </div>
            ))}
          </div>
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <article key={section.title} className="rounded-md border border-borderSoft bg-panel p-5 shadow-panel">
                <div className="flex items-start gap-3">
                  <div className="flex h-9 w-9 items-center justify-center rounded-md bg-panelMuted text-textMuted">
                    <Icon size={18} />
                  </div>
                  <div>
                    <h2 className="text-base font-semibold tracking-tight">{section.title}</h2>
                    <p className="mt-2 text-sm leading-6 text-textMuted">{section.body}</p>
                  </div>
                </div>
              </article>
            );
          })}
        </div>
      </section>

      <section className="mt-6 rounded-md border border-dashed border-borderSoft bg-panel p-5 shadow-panel">
        <div className="text-sm font-semibold">Placeholder scope</div>
        <p className="mt-2 text-sm leading-6 text-textMuted">
          Future AI explanations should cite the selected rules, show assumptions, and flag uncertainty.
          This prototype only demonstrates where that interpretation could appear.
        </p>
      </section>
    </>
  );
}
