"use client";

import { AlertTriangle, BookOpenText, CheckCircle2, Lightbulb, ShieldAlert } from "lucide-react";

import { PageHeader } from "@/components/page-header";
import { getStrategyRules } from "@/data/mock-data";
import { useStrategy } from "@/providers/strategy-provider";
import { runMockBacktest } from "@/services/mock-backtest-service";
import { generateMockResearchNotes } from "@/services/mock-research-service";
import { runMockScreener } from "@/services/mock-screener-service";
import type { ResearchSectionId } from "@/types/research";

const sectionIcons: Record<ResearchSectionId, typeof CheckCircle2> = {
  worked: CheckCircle2,
  risks: ShieldAlert,
  overfitting: AlertTriangle,
  costs: AlertTriangle,
  benchmark: ShieldAlert,
  improvements: Lightbulb
};

export function ResearchNotesPage() {
  const { strategy } = useStrategy();
  const enabledRules = getStrategyRules(strategy).filter((rule) => rule.enabled);
  const backtest = runMockBacktest(strategy);
  const screener = runMockScreener(strategy);
  const notes = generateMockResearchNotes(strategy, backtest, screener);

  return (
    <>
      <PageHeader
        eyebrow="Research Notes"
        title="Interpret the strategy without treating it as advice."
        description="These notes are mock educational explanations for the current configuration. They are not generated by an AI service and are not financial advice."
      />

      <section className="grid gap-6 xl:grid-cols-[420px_1fr]">
        <div className="rounded-md border border-borderSoft bg-panel p-5 shadow-panel">
          <div className="flex items-start gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-md bg-accentSoft text-accent">
              <BookOpenText size={20} />
            </div>
            <div>
              <h2 className="text-base font-semibold tracking-tight">Strategy summary</h2>
              <p className="mt-1 text-sm leading-6 text-textMuted">{notes.strategySummary}</p>
            </div>
          </div>

          <div className="mt-5 space-y-3">
            {enabledRules.map((rule) => (
              <div key={rule.label} className="rounded-md border border-borderSoft bg-panelMuted p-3">
                <div className="text-sm font-semibold">{rule.label}</div>
                <div className="mt-1 text-sm leading-6 text-textMuted">{rule.value}</div>
              </div>
            ))}
          </div>
        </div>

        <div className="grid gap-4 lg:grid-cols-2">
          {notes.sections.map((section) => {
            const Icon = sectionIcons[section.id];
            return (
              <article key={section.title} className="rounded-md border border-borderSoft bg-panel p-5 shadow-panel">
                <div className="flex items-start gap-3">
                  <div className="flex h-9 w-9 items-center justify-center rounded-md bg-panelMuted text-textMuted">
                    <Icon size={18} />
                  </div>
                  <div>
                    <h2 className="text-base font-semibold tracking-tight">{section.title}</h2>
                    <p className="mt-2 text-sm leading-6 text-textMuted">{section.body}</p>
                  </div>
                </div>
              </article>
            );
          })}
        </div>
      </section>

      <section className="mt-6 rounded-md border border-dashed border-borderSoft bg-panel p-5 shadow-panel">
        <div className="text-sm font-semibold">Placeholder scope</div>
        <p className="mt-2 text-sm leading-6 text-textMuted">{notes.disclaimer}</p>
      </section>
    </>
  );
}
